### ISSUE TITLE
Weird ImGui debug window

### ISSUE THREAD

**Issue by SightDev** [W1lliam1337/digital-sdk#11]
The window is there and I can't find anything that is labeled ImGui::Begin("debug");
I did some googlin' and found it ment that it started a ImGui::Begin(""); with no ImGui::End();
But I can't find anything that looks wrong am I missing something?

**Comment by W1lliam1337** [comment]
https://github.com/W1lliam1337/digital-sdk/blob/master/digital-sdk/dependencies/imgui/imgui.cpp#L3535

**Comment by codecheck01** [comment]
@W1lliam1337 It is a problem with your base, I will explain briefly the problem, you will know that in the future.

If you do any ImGui calls outside of Begin/End blocks, it will show the **implicit** Debug window.

So you can easily see that the problem is caused by this call: https://github.com/W1lliam1337/digital-sdk/blob/69686f10f3f7693bfd6bd90d2b1e2de6a3efd0fc/digital-sdk/cheat/menu/menu.cpp#L43

**PS**: I don't want to be rude, but you copy-pasted a lot of things from many bases, and you should at least understand what you are doing, when writing a clean sdk.

**Comment by codecheck01** [comment]
@W1lliam1337 If you want a clean base, rework the whole render system to work with a vanilla ImGui (not modified), and don't use the one from [**CSGOSimple**](https://github.com/spirthack/CSGOSimple).

**Comment by W1lliam1337** [comment]
> @W1lliam1337 If you want a clean base, rework the whole render system to work with a vanilla ImGui (not modified), and don't use the one from [**CSGOSimple**](https://github.com/spirthack/CSGOSimple).
> 
> ImGui без модиф лучше.
Write me what I copy-pasted from other bases, I'm very interested to know.
Perhaps a signature scan or a search for modules or a netvars manager, oh yes, it's the same everywhere, so I copy-pasted it.
I don’t want to be rude, but what nonsense are you talking about.
As for the render system, okay, I'll change it.
